#!/usr/bin/env python3
"""Regenerate kb/ index pages from doc frontmatter. Integrator-run only.

Indexes are BUILD ARTIFACTS (protocols/CONVENTIONS.md §Merge safety rule 2):
one `index.generated.md` per top-level kb/ section listing every doc's title,
topic and confidence. Hand-edited index files are a bug; curated overview
PROSE belongs in ordinary docs, not indexes.

No dependencies. Frontmatter parsing is deliberately minimal (key: value).
"""
from __future__ import annotations
import io, os, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "kb"

def frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8", errors="ignore")
    if not text.startswith("---"): return {}
    end = text.find("\n---", 3)
    if end < 0: return {}
    out = {}
    for line in text[3:end].splitlines():
        m = re.match(r"^(\w[\w-]*):\s*(.*)$", line)
        if m: out[m.group(1)] = m.group(2).strip().strip('"')
    return out

def main():
    if not ROOT.is_dir():
        sys.exit("no kb/ directory")
    sections: dict[str, list] = {}
    for p in sorted(ROOT.rglob("*.md")):
        if p.name == "index.generated.md": continue
        fm = frontmatter(p)
        if not fm.get("title"): continue
        section = p.relative_to(ROOT).parts[0] if len(p.relative_to(ROOT).parts) > 1 else "."
        sections.setdefault(section, []).append((p, fm))
    for section, docs in sections.items():
        dirp = ROOT / section if section != "." else ROOT
        lines = [f"# Index — {section if section != '.' else 'kb root'} ({len(docs)} docs)", "",
                 "_Generated by scripts/build_indexes.py — do not edit by hand._", ""]
        for p, fm in docs:
            rel = p.relative_to(dirp) if section != "." else p.relative_to(ROOT)
            bits = [f"[{fm['title']}]({rel})"]
            if fm.get("volatility"): bits.append(fm["volatility"])
            if fm.get("confidence"): bits.append(f"confidence {fm['confidence']}")
            if fm.get("last_verified"): bits.append(f"verified {fm['last_verified']}")
            lines.append("- " + " · ".join(bits))
        (dirp / "index.generated.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"wrote {dirp / 'index.generated.md'} ({len(docs)} entries)")

if __name__ == "__main__":
    main()
